function str(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre><i>public class</i> Test{</pre>";
		var s3 = "<pre>    <i>public static void</i> main(String[] args) {</pre>";
		var s4 = "<pre>        String str = \"abcdef\";</pre>";
		var s5 = "<pre>        String str1 = <i>new</i> String();</pre>";
		var s6 = "<pre>        <i>char</i> [] arr = {'a', 'b', 'c', 'd'};</pre>";
		var s7 = "<pre>        String str2 = <i>new</i> String(arr);</pre><br>";
		var s8 = "<pre>        System.out.println(str + \"\\n\" + str1.isEmpty() + \"\\n\" + str2);</pre>";
		var s9 = "<pre>    }</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = "";
		document.getElementById("cl11").innerHTML = "";
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("co1").innerHTML = "abcdef";
		document.getElementById("co2").innerHTML = "true";
		document.getElementById("co3").innerHTML = "abcd";
		document.getElementById("co4").innerHTML = "";
	}
	function strobj(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre><i>public class</i> Test{</pre>";
		var s3 = "<pre>    <i>public static void</i> main(String[] args) {</pre>";
		var s4 = "<pre>        String str = \"abcdef\";</pre>";
		var s5 = "<pre>        String str1 = <i>new</i> String();</pre>";
		var s6 = "<pre>        <i>char</i> [] arr = {'a', 'b', 'c'};</pre>";
		var s7 = "<pre>        String str2 = <i>new</i> String(arr);</pre><br>";
		var s6 = "<pre>        str1 = str;</pre>";
		var s7 = "<pre>        System.out.println(str.<i>equals</i>(str1));  <u>// str == str1 as objects</u></pre>";
		var s8 = "<pre>        System.out.println((str.<i>equals</i>\"abcdef\");  <u>//str != \"abcdef\" as objects</u></pre>";
		var s9 = "<pre>        System.out.println((str.<i>contentEquals</i>(\"abcdef\"));  <u>//str == \"abcdef\" by content</u></pre>";
		var s10 = "<pre>    }</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = "";
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("co1").innerHTML = "true";
		document.getElementById("co2").innerHTML = "false";
		document.getElementById("co3").innerHTML = "true";
		document.getElementById("co4").innerHTML = "";
	}
	function estrm(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre><i>public class</i> Test{</pre>";
		var s3 = "<pre>    <i>public static void</i> main(String[] args) {</pre>";
		var s4 = "<pre>        String str = \"abcdef\";</pre>";
		var s5 = "<pre>        String str1 = <i>new</i> String();</pre>";
		var s6 = "<pre>        str1 = \"Abcdef\";</pre>";
		var s7 = "<pre>        System.out.println(\"1)\" str.<i>equals</i>( \"abcdef\" ));</pre>";
		var s8 = "<pre>        System.out.println(\"2)\" str.<i>contentEquals</i>( \"abcdef\" ));</pre>";
		var s9 = "<pre>        System.out.println(\"3)\" str.<i>equals</i>(str1));</pre>";
		var s10 = "<pre>        System.out.println(\"4)\" str.<i>equalsIgnoreCase</i>(str1));</pre>";
		var s11 = "<pre>        System.out.println(\"5)\" str.<i>matches</i>( \"[a-z]*\" ));</pre>";
		var s12 = "<pre>        System.out.println(\"6)\" str.<i>compareTo</i>( \"str1\" ));</pre>";
		var s13 = "<pre>    }</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("co1").innerHTML = "1) false<br>2) true<br>3) false";
		document.getElementById("co2").innerHTML = "4) true<br> 5) true<br>6) 32";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
	}
	function gstrm(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre><i>public class</i> Test{</pre>";
		var s3 = "<pre>    <i>public static void</i> main(String[] args) {</pre>";
		var s4 = "<pre>        String str = \"abcdef\";</pre>";
		var s5 = "<pre>        System.out.println(\"1)\" str.<i>length</i>());</pre>";
		var s6 = "<pre>        System.out.println(\"2)\" str.<i>charAt</i>(2));</pre>";
		var s7 = "<pre>        System.out.println(\"3)\" str.<i>indexOf</i>('f'));</pre>";
		var s8 = "<pre>        System.out.println(\"4)\" str.<i>indexOf</i>('f', 2));</pre>";
		var s9 = "<pre>        System.out.println(\"5)\" str.<i>lastIndexOf</i>('f'));</pre>";
		var s10 = "<pre>        System.out.println(\"6)\" str.<i>substring</i>(3));</pre>";
		var s11 = "<pre>        System.out.println(\"7)\" str.<i>substring</i>(2, 4));</pre>";
		var s12 = "<pre>        System.out.println(\"8)\" str.<i>startsWith</i>(\"a\"));</pre>";
		var s13 = "<pre>        System.out.println(\"9)\" str.<i>endsWith</i>(\"f\"));</pre>";
		var s14 = "<pre>        System.out.println(\"10)\" str.<i>getBytes</i>());</pre>";
		var s15 = "<pre>        System.out.println(\"11)\" str.<i>hashCode</i>();</pre>";
		var s16 = "<pre>    }</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("co1").innerHTML = "1) 7<br>2) b<br>3) 0";
		document.getElementById("co2").innerHTML = "4) 6<br> 5) 6<br>6) cdef";
		document.getElementById("co3").innerHTML = "7) bc<br> 8) false<br>9) true";
		document.getElementById("co4").innerHTML = "10) [B@15db9742<br> 11) -1093323703";
	}
	function dstrm(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre><i>public class</i> Test{</pre>";
		var s3 = "<pre>    <i>public static void</i> main(String[] args) {</pre>";
		var s4 = "<pre>        String str = \"abcdef  \";</pre>";
		var s5 = "<pre>        String [] strm = str.<i>split</i>(\"c\");</pre>";
		var s6 = "<pre>        System.out.println(\"1)\" strm[0]);</pre>";
		var s7 = "<pre>        <i>char</i> [] c = str.<i>toCharArray</i>();</pre>";
		var s8 = "<pre>        System.out.println(\"2)\" c[0]);</pre>";
		var s9 = "<pre>        System.out.print(\"3)\" String.<i>copyValueOf</i>(c));</pre>";
		var s10 = "<pre>        str.<i>trim</i>();</pre>";
		var s11 = "<pre>        System.out.println(\"4)\" str.endsWith(\"  \"));</pre>";
		var s12 = "<pre>        System.out.println(\"5)\" str.<i>toUpperCase</i>());</pre>";
		var s13 = "<pre>        System.out.println(\"6)\" str.<i>toLowerCase</i>());</pre>";
		var s14 = "<pre>        System.out.println(\"7)\" str.<i>concat</i>( str ));</pre>";
		var s15 = "<pre>        System.out.println(\"8)\" str.<i>replace</i>(\'f\', \'v\'));</pre>";
		var s16 = "<pre>    }</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = s14;
		document.getElementById("cl15").innerHTML = s15;
		document.getElementById("cl16").innerHTML = s16;
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("co1").innerHTML = "1) ab<br>2) a<br>3) abcdef  ";
		document.getElementById("co2").innerHTML = "4) false<br> 5) ABCDEF<br>6) abcdef";
		document.getElementById("co3").innerHTML = "7) abcdefabcdef<br> 8) abcdev";
		document.getElementById("co4").innerHTML = "";
	}
	function strbuf(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre><i>public class</i> Test{</pre>";
		var s3 = "<pre>    <i>public static void</i> main(String[] args) {</pre>";
		var s4 = "<pre>        StringBuilder sb = <i>new</i> StringBuilder( \"xyz\" );</pre>";
		var s5 = "<pre>        <i>char</i> [] arr = {'a', 'b', 'c'};</pre>";
		var s6 = "<pre>        System.out.println(\"1)\" sb.<i>append</i>(sb));</pre>";
		var s7 = "<pre>        System.out.println(\"2)\" sb.<i>append</i>(arr));</pre>";
		var s8 = "<pre>        System.out.println(\"3)\" sb.<i>reverse</i>());</pre>";
		var s9 = "<pre>        System.out.println(\"4)\" sb.<i>delete</i>(0, 3));</pre>";
		var s10 = "<pre>        System.out.println(\"5)\" sb.<i>insert</i>(0, arr));</pre>";
		var s11 = "<pre>        System.out.println(\"6)\" sb.<i>replace</i>(4, 7, \"111\"));</pre>";
		var s12 = "<pre>    }</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("co1").innerHTML = "1) xyzxyz<br>2) xyzxyzabc<br>3) cbazyxzyx";
		document.getElementById("co2").innerHTML = "4) zyxzyx<br> 5) abczyxzyx<br>6) abc111yx";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
	}
	function clearr(){
		document.getElementById("cl1").innerHTML = "";
		document.getElementById("cl2").innerHTML = "";
		document.getElementById("cl3").innerHTML = "";
		document.getElementById("cl4").innerHTML = "";
		document.getElementById("cl5").innerHTML = "";
		document.getElementById("cl6").innerHTML = "";
		document.getElementById("cl7").innerHTML = "";
		document.getElementById("cl8").innerHTML = "";
		document.getElementById("cl9").innerHTML = "";
		document.getElementById("cl10").innerHTML = "";
		document.getElementById("cl11").innerHTML = "";
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("co1").innerHTML = "";
		document.getElementById("co2").innerHTML = "";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
	}