	function colm(){
		var s1 = "<br><pre><i>public interface</i> Collection <i>extends</i> Iterable&lt;E&gt;{</pre>";
		var s2 = "<pre>    <int> size();</pre><pre>    <i>boolean</i> isEmpty();</pre><pre>    <i>boolean</i> contains( Object o);</pre>";
		var s3 = "<pre>    Iterator &lt;E&gt; iterator();</pre><pre>    Object [] toArray();</pre><pre>    &lt;E&gt; T[] toArray(T[] a);</pre>";
		var s4 = "<pre>    <i>boolean</i> add(E e);</pre><pre>    <i>boolean</i> remove( Object o);</pre>";
		var s5 = "<pre>    <i>boolean</i> containsAll( Collection&lt;?&gt; c);</pre>";
		var s6 = "<pre>    <i>boolean</i> addAll( Collection&lt;? <i>extends</i> E&gt; c);</pre>";
		var s7 = "<pre>    <i>boolean</i> removeAll( Collection&lt;?&gt; c);</pre>";
		var s8 = "<pre>    <i>default boolean</i> removeif( Predicate&lt;? <i>super</i> E&gt; filter){</pre>";
		var s9 = "<pre>        Objects.requireNonNull(filter);</pre><pre>        <i>boolean</i> removed = <i>false</i>;</pre>";
		var s10 = "<pre>        <i>final</i> Iterator &lt;E&gt; each = iterator();</pre><pre>        <i>while</i> (each.hasNext()) {</pre>";
		var s11 = "<pre>            <i>if</i> (filter.test(each.next())){</pre><pre>                each.remove();</pre>";
		var s12 = "<pre>                removed = <i>true</i>;</pre><pre>            }</pre><pre>        }</pre><pre>         <i>return</i> removed;</pre><pre>    }</pre>";
		var s13 = "<pre>    <i>boolean</i> retainAll( Collection&lt;?&gt; c);</pre>";
		var s14 = "<pre>    <i>void</i> clear();</pre><pre>    <i>void</i> equals(Object o);</pre><pre>    <i>int</i> hashCode();</pre>";
		var s15 = "<pre>    <i>default</i> spliterator&lt;E&gt; spliterator(){</pre>";
		var s16 = "<pre>         <i>return</i> spliterators.spliterator(<i>this</i>, 0);</pre><pre>    }</pre>";
		var s17 = "<pre>    <i>default</i> Stream&lt;E&gt; stream(){</pre>";
		var s18 = "<pre>         <i>return</i> StreamSupport.stream(spliterator(), <i>false</i>);</pre><pre>    }</pre>";
		var s19 = "<pre>    <i>default</i> Stream&lt;E&gt; parallelStream(){</pre>";
		var s20 = "<pre>         <i>return</i> StreamSupport.stream(spliterator(), <i>true</i>);</pre><pre>    }</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = s14;
		document.getElementById("cl15").innerHTML = s15;
		document.getElementById("cl16").innerHTML = s16;
		document.getElementById("cl17").innerHTML = s17;
		document.getElementById("cl18").innerHTML = s18;
		document.getElementById("cl19").innerHTML = s19;
		document.getElementById("cl20").innerHTML = s20;
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("cl23").innerHTML = "";
	}

	function clearr(){
		document.getElementById("cl1").innerHTML = "";
		document.getElementById("cl2").innerHTML = "";
		document.getElementById("cl3").innerHTML = "";
		document.getElementById("cl4").innerHTML = "";
		document.getElementById("cl5").innerHTML = "";
		document.getElementById("cl6").innerHTML = "";
		document.getElementById("cl7").innerHTML = "";
		document.getElementById("cl8").innerHTML = "";
		document.getElementById("cl9").innerHTML = "";
		document.getElementById("cl10").innerHTML = "";
		document.getElementById("cl11").innerHTML = "";
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("cl23").innerHTML = "";
		document.getElementById("co1").innerHTML = "";
		document.getElementById("co2").innerHTML = "";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
	}