function arq(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre><i>import</i> java.util.ArrayDeque;</pre><br>";
		var s3 = "<pre><i>public class</i> Test{</pre>";
		var s4 = "<pre>    ArrayDeque &lt;Integer&gt; arrq1 = <i>new</i> ArrayDeque&lt; &gt;(); <u>//simple queue</u></pre>";
		var s5 = "<pre>    ArrayDeque &lt;String&gt; arrq2 = <i>new</i> ArrayDeque&lt; &gt;(10); <u>//queue with initial capacity</u></pre>";
		var s6 = "<pre>    ArrayDeque &lt;Object&gt; arrq3 = <i>new</i> ArrayDeque&lt; &gt;(arrq2); <u>//queue with elements of other queue</u></pre>";
		var s7 = "<pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = " ";
		document.getElementById("cl9").innerHTML = " ";
		document.getElementById("cl10").innerHTML = " ";
		document.getElementById("cl11").innerHTML = " ";
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("cl23").innerHTML = "";
	}
	function arqm(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre><i>import</i> java.util.ArrayList;</pre><br>";
		var s3 = "<pre><i>public class</i> Test{</pre>";
		var s4 = "<pre>    <i>public static void</i> main(String[] args) {</pre>";
		var s5 = "<pre>        ArrayDeque &lt;String&gt; meal = <i>new</i> ArrayDeque&lt; &gt;();</pre>";
		var s6 = "<pre>        meal.<i>add</i>(\"spaghetti\");</pre><pre>        countries.<i>addFirst</i>(\"buckweat\");</pre>";
		var s7 = "<pre>        meal.<i>push</i>(\"spaghetti\");</pre><pre>        countries.<i>addLast</i>(\"buckweat\");</pre>";
		var s8 = "<pre>        meal.<i>add</i>(\"spaghetti\");</pre>";
		var s9 = "<pre>        System.out.println(\"1)\" + meal.<i>getFirst</i>() );</pre>";
		var s10 = "<pre>        System.out.println(\"2)\" + meal.<i>getLast</i>() );</pre>";
		var s11 = "<pre>        System.out.println(\"3)\" + meal.<i>size</i>() );</pre>";
		var s12 = "<pre>        while(meal.<i>peek</i>() != null){ <u>//take without remove</u></pre>";
		var s13 = "<pre>            System.out.printl(meal.<i>pop</i>() + \"  \");</pre><pre>        }</pre>";
		var s14 = "<pre>        System.out.println(\"4)\" + meal.<i>size</i>() );</pre><br>";
		var s15 = "<pre>        ArrayDeque &lt;Cat&gt; cats = <i>new</i> Cat&lt; &gt;();</pre>";
		var s16 = "<pre>        cats.<i>addFirst</i>(\"Tom\");</pre><pre>        cats.<i>addLast</i>(\"Jack\");</pre>";
		var s17 = "<pre>        for(Cat c: cats){</pre><pre>            System.out.printl(c.<i>getName</i>() + \"  \");</pre><pre>        }</pre>";
		var s18 = "<pre>        System.out.println(\"5)\" + cats.<i>size</i>() );</pre><pre>    }</pre><pre>}</pre><br>";
		var s19 = "<pre><i>class</i> Cat{</pre><pre>    <i>private</i> String name;</pre><pre>    <i>public</i> Cat(String value){</pre>";
		var s20 = "<pre>            name = value;</pre><pre>    }</pre><pre>        String getName(){<i>return</i> name;</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = s14;
		document.getElementById("cl15").innerHTML = s15;
		document.getElementById("cl16").innerHTML = s16;
		document.getElementById("cl17").innerHTML = s17;
		document.getElementById("cl18").innerHTML = s18;
		document.getElementById("cl19").innerHTML = s19;
		document.getElementById("cl20").innerHTML = s20;
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("cl23").innerHTML = "";
		document.getElementById("co1").innerHTML = "1) ragout<br>2) cake<br>3) 5";
		document.getElementById("co2").innerHTML = "ragout buckwheat spaghetti roast cake ";
		document.getElementById("co3").innerHTML = "4) 0<br>Tom Jack <br>5) 2";
		document.getElementById("co4").innerHTML = "";
	}

	function clearr(){
		document.getElementById("cl1").innerHTML = "";
		document.getElementById("cl2").innerHTML = "";
		document.getElementById("cl3").innerHTML = "";
		document.getElementById("cl4").innerHTML = "";
		document.getElementById("cl5").innerHTML = "";
		document.getElementById("cl6").innerHTML = "";
		document.getElementById("cl7").innerHTML = "";
		document.getElementById("cl8").innerHTML = "";
		document.getElementById("cl9").innerHTML = "";
		document.getElementById("cl10").innerHTML = "";
		document.getElementById("cl11").innerHTML = "";
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("cl23").innerHTML = "";
		document.getElementById("co1").innerHTML = "";
		document.getElementById("co2").innerHTML = "";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
	}