function lili(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre><i>import</i> java.util.ArrayList;</pre><br>";
		var s3 = "<pre><i>public class</i> Test{</pre>";
		var s4 = "<pre>    LinkedList &lt;String&gt; clothes = <i>new</i> LinkedList&lt; &gt;();</pre>";
		var s5 = "<pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = "";
		document.getElementById("cl7").innerHTML = "";
		document.getElementById("cl8").innerHTML = " ";
		document.getElementById("cl9").innerHTML = " ";
		document.getElementById("cl10").innerHTML = " ";
		document.getElementById("cl11").innerHTML = " ";
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("cl23").innerHTML = "";
	}
	function lilinod(){
		var s1 = "<pre><br><i>private static class</i> Node&lt;E&gt; {</pre>";
		var s2 = "<pre>    E <i>item</i>; </pre>";
		var s3 = "<pre>    Node&lt;E&gt; <i>next</i>;</pre>";
		var s4 = "<pre>    Node&lt;E&gt; <i>prev</i>;</pre><br>";
		var s5 = "<pre>    Node(Node&lt;E&gt; prev, E element, Node&lt;E&gt; next){</pre>";
		var s6 = "<pre>        <i>this</i>.element = element;</pre>";
		var s7 = "<pre>        <i>this</i>.next = next;</pre>";
		var s8 = "<pre>        <i>this</i>.prev = prev;</pre><pre>    }</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = " ";
		document.getElementById("cl10").innerHTML = " ";
		document.getElementById("cl11").innerHTML = " ";
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("cl23").innerHTML = "";
		document.getElementById("co1").innerHTML = "";
		document.getElementById("co2").innerHTML = "";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
	}
	function lilim(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre><i>import</i> java.util.ArrayList;</pre><br>";
		var s3 = "<pre><i>public class</i> Test{</pre>";
		var s4 = "<pre>    <i>public static void</i> main(String[] args) {</pre>";
		var s5 = "<pre>        LinkedList &lt;String&gt; clothes = <i>new</i> LinkedList&lt; &gt;();</pre>";
		var s6 = "<pre>        clothes.<i>add</i>(\"pants\");</pre><pre>        clothes.<i>add</i>(\"socks\");</pre>";
		var s7 = "<pre>        clothes.<i>addLast</i>(\"hat\");</pre><pre>        clothes.<i>addFirst</i>(\"coat\");</pre>";
		var s8 = "<pre>        clothes.<i>add</i>(1, \"skirt\");</pre>";
		var s9 = "<pre>        System.out.println(\"1)\" + clothes +  \",  \" + clothes.<i>size</i>());</pre>";
		var s10 = "<pre>        System.out.println(\"2)\" + clothes.<i>get</i>(1));</pre>";
		var s11 = "<pre>        clothes.<i>set</i>(1, \"dress\");</pre>";
		var s12 = "<pre>        System.out.println(\"3)\" + clothes +  \",  \" + clothes.<i>size</i>());</pre>";
		var s13 = "<pre>        if (clothes.<i>contains</i>(\"hat\"));</pre>";
		var s14 = "<pre>            System.out.println(\"we have a hat \");</pre><pre>        }</pre>";
		var s15 = "<pre>        clothes.<i>remove</i>(\"coat\");</pre>";
		var s16 = "<pre>        System.out.println(\"4)\" + clothes.<i>get</i>(0));</pre>";
		var s17 = "<pre>        clothes.<i>removeFirst</i>();</pre>";
		var s18 = "<pre>        System.out.println(\"5)\" + clothes.<i>get</i>(0));</pre>";
		var s19 = "<pre>        clothes.<i>remove</i>(0);</pre>";
		var s20 = "<pre>        System.out.println(\"6)\" + clothes.<i>get</i>(0));</pre><pre>    }</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = s14;
		document.getElementById("cl15").innerHTML = s15;
		document.getElementById("cl16").innerHTML = s16;
		document.getElementById("cl17").innerHTML = s17;
		document.getElementById("cl18").innerHTML = s18;
		document.getElementById("cl19").innerHTML = s19;
		document.getElementById("cl20").innerHTML = s20;
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("cl23").innerHTML = "";
		document.getElementById("co1").innerHTML = "1) [coat, skirt, pants, socks, hat], 5<br>2) skirt";
		document.getElementById("co2").innerHTML = "3) [coat, dress, pants, socks, hat], 5<br>we have hat";
		document.getElementById("co3").innerHTML = "4) dress<br>5) pants<br>6) socks";
		document.getElementById("co4").innerHTML = "";
	}

	function clearr(){
		document.getElementById("cl1").innerHTML = "";
		document.getElementById("cl2").innerHTML = "";
		document.getElementById("cl3").innerHTML = "";
		document.getElementById("cl4").innerHTML = "";
		document.getElementById("cl5").innerHTML = "";
		document.getElementById("cl6").innerHTML = "";
		document.getElementById("cl7").innerHTML = "";
		document.getElementById("cl8").innerHTML = "";
		document.getElementById("cl9").innerHTML = "";
		document.getElementById("cl10").innerHTML = "";
		document.getElementById("cl11").innerHTML = "";
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("cl23").innerHTML = "";
		document.getElementById("co1").innerHTML = "";
		document.getElementById("co2").innerHTML = "";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
	}