function objdef() {
		var s1 = "<pre><i>class</i> Test { //<u><--- top level class</u></pre><br>";
		var s2 = "<pre>    Test() {	... }    <u>// constructor</u></pre>";
		var s3 = "<pre>    <i>void</i> m() { ... }    <u>// method</u></pre>";
		var s4 = "<pre>    <i>int</i> x;    <u>// field</u></pre>";
		var s5 = "<pre>    { ... }    <u>// initialized block</u></pre>";
		var s6 = "<pre>    <i>class</i> A {}    <u>// internal class</u></pre><br>";
		var s7 = "<pre>    <u>// static elements belong to class</u></pre><br>";
		var s8 = "<pre>    <i>static int</i> x2;    <u>// static fields</u></pre>";
		var s9 = "<pre>    <i>static void</i> m2() {/*...*/} <u>// static methods</u></pre>";
		var s10 = "<pre>    <i>static</i> {}    <u>// static initialized block</u></pre><br>";
		var s11 = "<pre>    <i>static class</i> A2 {}    <u>// nested classes</u></pre>";
		var s12 = "<pre>    <i>interface</i> G {}    <u>// nested interface</u></pre><br>";
		var s13 = "<pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("co1").innerHTML = "";
		document.getElementById("co2").innerHTML = "";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
		document.getElementById("co5").innerHTML = "";
		document.getElementById("co6").innerHTML = "";
		document.getElementById("co7").innerHTML = "";
		document.getElementById("co8").innerHTML = "";
	}
	function objgo() {
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre><i>class</i> Test {</pre>";
		var s3 = "<pre>    <i>static</i> String x2;</pre><br><pre>    <i>static</i> {</pre>";
		var s4 = "<pre>        Test.x2 = \"static initialized block\"</pre>";
		var s5 = "<pre>        System.out.println(\"1: \" + x2);</pre><pre>    }</pre><br><pre>    {</pre>";
		var s6 = "<pre>        x2 = \"initialized block\"</pre>";
		var s7 = "<pre>        System.out.println(\"2: \" + x2);</pre><pre>    }</pre><br>";
		var s8 = "<pre>    Test(){</pre><pre>        x2 = \"constructor\"</pre>";
		var s9 = "<pre>        System.out.println(\"3: \" + x2);</pre><pre>    }</pre><br>";
		var s10 = "<pre>    <i>class</i> A {</pre><pre>        {x2 = \"internal class A\"</pre>";
		var s11 = "<pre>        System.out.println(x2);}</pre><pre>    }</pre>";
		var s12 = "<pre>    <i>class</i> B <i>extends</i> A {</pre>";
		var s13 = "<pre>        { x2 = \"internal class B extends A\"</pre>";
		var s14 = "<pre>        System.out.println(x2);}</pre><pre>    }</pre>";
		var s15 = "<pre>    <i>static class</i> C <i>extends</i> A {</pre>";
		var s16 = "<pre>        { x2 = \"nested (static) class C\"</pre>";
		var s17 = "<pre>        System.out.println(x2);}</pre><pre>    }</pre><br>";
		var s18 = "<pre>     A a1 = <i>new</i> A();    <u>// a1 - example of A</u></pre>";
		var s19 = "<pre>     B a2 = <i>new</i> A();</pre><pre>     B a3 = <i>new</i> B();</pre><br>";
		var s20 = "<pre>        <i>public static void</i> main(String[] args) {</pre>";
		var s21 = "<pre>        System.out.println(<i>new</i> Test());</pre>";
		var s22 = "<pre>        System.out.println(<i>new</i> Test.C());</pre><pre>    }</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = s14;
		document.getElementById("cl15").innerHTML = s15;
		document.getElementById("cl16").innerHTML = s16;
		document.getElementById("cl17").innerHTML = s17;
		document.getElementById("cl18").innerHTML = s18;
		document.getElementById("cl19").innerHTML = s19;
		document.getElementById("cl20").innerHTML = s20;
		document.getElementById("cl21").innerHTML = s21;
		document.getElementById("cl22").innerHTML = s22;
		document.getElementById("co1").innerHTML = "1: static initialized block";
		document.getElementById("co2").innerHTML = "2: initialized block";
		document.getElementById("co3").innerHTML = "internal class A";
		document.getElementById("co4").innerHTML = "nested (static) class C";
		document.getElementById("co5").innerHTML = "internal class A";
		document.getElementById("co6").innerHTML = "internal class B extends A";
		document.getElementById("co7").innerHTML = "3: constructor";
		document.getElementById("co8").innerHTML = "nested (static) class C";
	}
	function objmetdef(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre><i>class</i> Test {</pre>";
		var s3 = "<pre>    <i>static</i> String x2;</pre>";
		var s4 = "<pre>    <i>static</i> { System.out.println(\"1: static initialized block\"); }</pre>";
		var s5 = "<pre>    { System.out.println(\"2: initialized block\"); }</pre>";
		var s6 = "<pre>    Test(){</pre><pre>        System.out.println(\"3: constructor\");</pre><pre>    }</pre><br>";
		var s7 = "<pre>    <i>void</i> m() {</pre><pre>        x2 = \"method\"</pre>";
		var s8 = "<pre>        System.out.println(x2);</pre><pre>    }</pre>";
		var s9 = "<pre>    <i>static void</i> m2() {</pre>";
		var s10 = "<pre>        x2 = \"static method\"</pre>";
		var s11 = "<pre>        System.out.println(x2);</pre><pre>    }</pre>";
		var s12 = "<pre>    <i>static void</i> m2(<i>int</i> i) {</pre>";
		var s13 = "<pre>        x2 = \"static method with argument\"</pre>";
		var s14 = "<pre>        System.out.println(x2 + i);</pre><pre>    }</pre><br>";
		var s15 = "<pre>    <i>static</i> String m3() {</pre>";
		var s16 = "<pre>        x2 = \"method returns x2\"</pre>";
		var s17 = "<pre>        return x2;</pre><pre>    }</pre>";
		var s18 = "<pre>        <i>public static void</i> main(String[] args) {</pre>";
		var s19 = "<pre>        <u>// Test.m(); // error</u></pre>";
		var s20 = "<pre>        Test.m2();</pre><pre>        Test.m2(1);</pre>";
		var s21 = "<pre>        System.out.println(Test.m3());</pre><pre>    }</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = s14;
		document.getElementById("cl15").innerHTML = s15;
		document.getElementById("cl16").innerHTML = s16;
		document.getElementById("cl17").innerHTML = s17;
		document.getElementById("cl18").innerHTML = s18;
		document.getElementById("cl19").innerHTML = s19;
		document.getElementById("cl20").innerHTML = s20;
		document.getElementById("cl21").innerHTML = s21;
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("co1").innerHTML = "1: static initialized block";
		document.getElementById("co2").innerHTML = "static method";
		document.getElementById("co3").innerHTML = "method with argument 1";
		document.getElementById("co4").innerHTML = "method returns x2";
		document.getElementById("co5").innerHTML = "";
		document.getElementById("co6").innerHTML = "";
		document.getElementById("co7").innerHTML = "";
		document.getElementById("co8").innerHTML = "";

	}

	function clearr(){
		document.getElementById("cl1").innerHTML = "";
		document.getElementById("cl2").innerHTML = "";
		document.getElementById("cl3").innerHTML = "";
		document.getElementById("cl4").innerHTML = "";
		document.getElementById("cl5").innerHTML = "";
		document.getElementById("cl6").innerHTML = "";
		document.getElementById("cl7").innerHTML = "";
		document.getElementById("cl8").innerHTML = "";
		document.getElementById("cl9").innerHTML = "";
		document.getElementById("cl10").innerHTML = "";
		document.getElementById("cl11").innerHTML = "";
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
	}
	function clearrc(){
		document.getElementById("co1").innerHTML = "";
		document.getElementById("co2").innerHTML = "";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
		document.getElementById("co5").innerHTML = "";
		document.getElementById("co6").innerHTML = "";
		document.getElementById("co7").innerHTML = "";
		document.getElementById("co8").innerHTML = "";
		document.getElementById("co9").innerHTML = "";
		document.getElementById("co10").innerHTML = "";
	}