
	function gener(){
		var s1 = "<pre><i>class</i> A &lt;T&gt; {...} <u> // параметризованный класс</u></pre><br>";
		var s2 = "<pre><i>public</i> &lt;T&gt; A(){...} <u> // параметризованный конструктор</u></pre><br>";
		var s3 = "<pre><i>public</i> &lt;T&gt; T method(T var){...} <u> // параметризованный метод</u></pre><br>";
		var s4 = "<pre><u> // Т - параметр генерика</u></pre><br>";
		var s5 = "<pre>A &lt;String&gt; a = <i>new</i> A&lt;String&gt;();<u> // параметризация параметризованного класса А</u></pre>";
		var s6 = "<pre>A &lt;Character&gt; a = <i>new</i> A&lt;&gt;();</pre><br>";
		var s7 = "<pre>A a = <i>new</i> A(); <u> // raw type - сырой тип</u></pre><br>";
		var s8 = "<pre>A &lt;?&gt; a = <i>new</i> A &lt;String&gt;(); <u> // Wildcard параметризованный класс</u></pre>";
		var s9 = "<pre>A &lt;? <i>extends</i> Number&gt; a = <i>new</i> A &lt;Integer&gt;();</pre>";
		var s10 = "<pre>A &lt;? <i>super</i> Integer&gt; a = <i>new</i> A &lt;Number&gt;();</pre><br>";
		var s11 = "<pre>List &lt;String&gt; [ ] ar; <u> // объявление переменной типа массив</u></pre>";
		var s12 = "<pre><u> //ar = new ArrayList &lt;String&gt; [ ]; // создание массива - ошибка!</u></pre>";
		var s13 = "<pre>List &lt;?&gt; [ ] x = <i>new</i> ArrayList &lt;?&gt; [3]; <u> // создание массива с использовнием &lt;?&gt;</u></pre><br>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("co1").innerHTML = "";
		document.getElementById("co2").innerHTML = "";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
	}
	function paramm(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre>    <i>public class</i> Test{</pre>";
		var s3 = "<pre>        &lt;T&gt; T method(T var){</pre>";
		var s4 = "<pre>              System.out.println(var);</pre>";
		var s5 = "<pre>              <i>return</i> var;</pre>";
		var s6 = "<pre>           }</pre><br>";
		var s7 = "<pre>         <i>public static void</i> main(String[] args) {</pre>";
		var s8 = "<pre>            Test m = <i>new</i> Test();</pre>";
		var s9 = "<pre>            <i>int</i> a = m.&lt;Integer&gt;method(1);</pre>";
		var s10 = "<pre>            <u>//int b = m.&lt;String&gt;method(2); //<-- error</pre>";
		var s11 = "<pre>            <i>int</i> c = m.method(3);</pre>";
		var s12 = "<pre>            <i>String</i> d = m.&lt;String&gt;method(\"4\");</pre>";
		var s13 = "<pre>            <i>String</i> e = m.method(\"5\");</pre>";
		var s14 = "<pre>        }</pre>";
		var s15 = "<pre>    }</pre><br>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = s14;
		document.getElementById("cl15").innerHTML = s15;
		document.getElementById("co1").innerHTML = "1";
		document.getElementById("co2").innerHTML = "3";
		document.getElementById("co3").innerHTML = "4";
		document.getElementById("co4").innerHTML = "5";
	}
	function parammm(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre>    <i>public class</i> Test{</pre>";
		var s3 = "<pre>        &lt;T, U&gt; <i>void</i> method(T t, U u){</pre>";
		var s4 = "<pre>              System.out.println(t+\" \"+u);</pre>";
		var s5 = "<pre>           }</pre><br>";
		var s6 = "<pre>         <i>public static void</i> main(String[] args) {</pre>";
		var s7 = "<pre>            Test m = <i>new</i> Test();</pre>";
		var s8 = "<pre>            m.&lt;Integer, Boolean&gt;method(1, true);</pre>";
		var s9 = "<pre>            m.method(2, \"3\");</pre>";
		var s10 = "<pre>        }</pre>";
		var s11 = "<pre>    }</pre><br>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("co1").innerHTML = "1 true";
		document.getElementById("co2").innerHTML = "2 3";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
	}
	function paramc(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre>    <i>public class</i> Test &lt;T&gt;{</pre>";
		var s3 = "<pre>        <i>T</i> method(T var){</pre>";
		var s4 = "<pre>              System.out.println(var);</pre>";
		var s5 = "<pre>              <i>return</i> var;</pre>";
		var s6 = "<pre>           }</pre><br>";
		var s7 = "<pre>         <i>public static void</i> main(String[] args) {</pre>";
		var s8 = "<pre>            Test &lt;Integer&gt; i = <i>new</i> Test&lt; &gt;();</pre>";
		var s9 = "<pre>            <i>int</i> a = i.method(1);</pre>";
		var s10 = "<pre>            Test &lt;String&gt; s = <i>new</i> Test&lt; &gt;();</pre>";
		var s11 = "<pre>            <i>String</i> b = s.method(\"2\");</pre>";
		var s12 = "<pre>        }</pre>";
		var s13 = "<pre>    }</pre><br>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("co1").innerHTML = "1";
		document.getElementById("co2").innerHTML = "2";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
	}
	function paramt(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre>    <i>class</i> Cloud {</pre><br>";
		var s3 = "<pre>    }</pre><br>";
		var s4 = "<pre>    <i>public class</i> Test &lt;T&gt;{</pre>";
		var s5 = "<pre>        <i>T</i> var;</pre>";
		var s6 = "<pre>         <i>public static void</i> main(String[] args) {</pre>";
		var s7 = "<pre>            Test &lt;CLoud&gt; c = <i>new</i> Test&lt; &gt;();</pre>";
		var s8 = "<pre>            c.var = <i>new</i> Cloud();</pre>";
		var s9 = "<pre>        }</pre>";
		var s10 = "<pre>    }</pre><br>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = "";
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("co1").innerHTML = "";
		document.getElementById("co2").innerHTML = "";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
	}

	function clearr(){
		document.getElementById("cl1").innerHTML = "";
		document.getElementById("cl2").innerHTML = "";
		document.getElementById("cl3").innerHTML = "";
		document.getElementById("cl4").innerHTML = "";
		document.getElementById("cl5").innerHTML = "";
		document.getElementById("cl6").innerHTML = "";
		document.getElementById("cl7").innerHTML = "";
		document.getElementById("cl8").innerHTML = "";
		document.getElementById("cl9").innerHTML = "";
		document.getElementById("cl10").innerHTML = "";
		document.getElementById("cl11").innerHTML = "";
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("co1").innerHTML = "";
		document.getElementById("co2").innerHTML = "";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
		document.getElementById("co5").innerHTML = "";
		document.getElementById("co6").innerHTML = "";
		document.getElementById("co7").innerHTML = "";
		document.getElementById("co8").innerHTML = "";
		document.getElementById("co9").innerHTML = "";
		document.getElementById("co10").innerHTML = "";
	}