function classdef() {
		var s = "<pre><i>package</i> com.mypackage;</pre><br>";
		document.getElementById("cl1").innerHTML = s;
		var s1 = "<pre>        <i>class</i> A {</pre>";
		var s2 = "<pre>        }</pre>";
		document.getElementById("cl2").innerHTML = s1;
		document.getElementById("cl3").innerHTML = s2;
		document.getElementById("cl3").innerHTML = "";
		document.getElementById("cl4").innerHTML = "";
		document.getElementById("cl5").innerHTML = "";
		document.getElementById("cl6").innerHTML = "";
	}
	function classex() {
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre>        <i>class</i> A {</pre>";
		var s3 = "<pre>        }</pre>";
		var s4 = "<pre>    <i>public class</i> My {</pre>";
		var s5 = "<pre>        A a1 = <i>new</i> A();</pre>";
		var s6 = "<pre>    }</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = "";
		document.getElementById("cl8").innerHTML = "";
		document.getElementById("cl9").innerHTML = "";
	}
	function classexdo(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre>        <i>class</i> A {</pre>";
		var s3 = "<pre>             <i>int</i> m(){</pre>";
		var s4 = "<pre>                return 1;</pre>";
		var s5 = "<pre>            }</pre>";
		var s6 = "<pre>        }</pre>";
		var s7 = "<pre>    <i>public class</i> My {</pre>";
		var s8 = "<pre>        <i>public static void</i> main(String[] args) {</pre>";
		var s9 = "<pre>            A a1 = <i>new</i> A();</pre>";
		var s10 = "<pre>            System.out.println(a1.m());</pre>";
		var s11 = "<pre>        }</pre>";
		var s12 = "<pre>    }</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("co1").innerHTML = "1";
	}
	function classexa(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre>    <i>class</i> A {</pre>";
		var s3 = "<pre>        <i>void</i> m(SomeClass p) {…}{</pre>";
		var s4 = "<pre>        <i>class</i> B {} <u>// класс элемент класса</u></pre>";
		var s5 = "<pre>        <i>void</i> m() {</pre>";
		var s6 = "<pre>            <i>class</i> C {} <u>// локальный класс</u></pre>";
		var s7 = "<pre>            m(<i>new</i> SomeClass() { <u>// анонимный класс</u></pre>";
		var s8 = "<pre>            });</pre><pre>        }</pre><pre>    }</pre>";
		var s9 = "<pre>    <i>abstract class</i> D {</pre>";
		var s10 = "<pre>        <i>abstract void</i> m1();</pre>";
		var s11 = "<pre>        <i>void</i> m2(){ <u>/*...*/</u> }</pre><pre>    }</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("co1").innerHTML = "";
	}
	function classinfil(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre>    <i>class</i> A {</pre>";
		var s3 = "<pre>        <i>private int</i> x;</pre>";
		var s4 = "<pre>        <i>class</i> B {</pre>";
		var s5 = "<pre>            <i>int</i> x = A.<i>this</i>.x;</pre>";
		var s6 = "<pre>        }</pre>";
		var s7 = "<pre>    }</pre>";
		var s8 = "<pre>    <i>class</i> Test {</pre>";
		var s9 = "<pre>        <i>public static void</i> main(String[] args) {</pre>";
		var s10 = "<pre>            A a = <i>new</i> A();</pre>";
		var s11 = "<pre>            A.B b = a.<i>new</i> B();</pre>";
		var s12 = "<pre>        }</pre>";
		var s13 = "<pre>    }</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("co1").innerHTML = "";
		}
	function classinel(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre>    <i>class</i> A {</pre>";
		var s3 = "<pre>        <i>class</i> B {}</pre>";
		var s4 = "<pre>    }</pre>";
		var s5 = "<pre>    <i>class</i> Test {</pre>";
		var s6 = "<pre>        <i>public static void</i> main(String[] args) {</pre>";
		var s7 = "<pre>            A a = <i>new</i> A();</pre>";
		var s8 = "<pre>            A.B b = a.<i>new</i> B();</pre>";
		var s9 = "<pre>        }</pre>";
		var s10 = "";
		var s11 = "";
		var s12 = "";
		var s13 = "";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("co1").innerHTML = "";
	}
	function clearr(){
		document.getElementById("cl1").innerHTML = "";
		document.getElementById("cl2").innerHTML = "";
		document.getElementById("cl3").innerHTML = "";
		document.getElementById("cl4").innerHTML = "";
		document.getElementById("cl5").innerHTML = "";
		document.getElementById("cl6").innerHTML = "";
		document.getElementById("cl7").innerHTML = "";
		document.getElementById("cl8").innerHTML = "";
		document.getElementById("cl9").innerHTML = "";
		document.getElementById("cl10").innerHTML = "";
		document.getElementById("cl11").innerHTML = "";
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("co1").innerHTML = "";
		document.getElementById("co2").innerHTML = "";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
		document.getElementById("co5").innerHTML = "";
		document.getElementById("co6").innerHTML = "";
		document.getElementById("co7").innerHTML = "";
		document.getElementById("co8").innerHTML = "";
		document.getElementById("co9").innerHTML = "";
		document.getElementById("co10").innerHTML = "";
	}