function arli(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre><i>import</i> java.util.ArrayList;</pre><br>";
		var s3 = "<pre><i>public class</i> Test{</pre>";
		var s4 = "<pre>    ArrayList &lt;String&gt; countries = <i>new</i> ArrayList&lt; &gt;();</pre>";
		var s5 = "<pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = "";
		document.getElementById("cl7").innerHTML = "";
		document.getElementById("cl8").innerHTML = " ";
		document.getElementById("cl9").innerHTML = " ";
		document.getElementById("cl10").innerHTML = " ";
		document.getElementById("cl11").innerHTML = " ";
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("cl23").innerHTML = "";
	}
	function arlim(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre><i>import</i> java.util.ArrayList;</pre><br>";
		var s3 = "<pre><i>public class</i> Test{</pre>";
		var s4 = "<pre>    <i>public static void</i> main(String[] args) {</pre>";
		var s5 = "<pre>        ArrayList &lt;String&gt; countries = <i>new</i> ArrayList&lt; &gt;();</pre>";
		var s6 = "<pre>        countries.<i>add</i>(\"Ukraine\");</pre><pre>        countries.<i>add</i>(\"Germany\");</pre>";
		var s7 = "<pre>        System.out.println(\"1)\" + countries );</pre>";
		var s8 = "<pre>        System.out.println(\"2)\" + countries.<i>size</i>() );</pre>";
		var s9 = "<pre>        System.out.println(\"3)\" + countries.<i>sublist</i>(0, 1) );</pre>";
		var s10 = "<pre>        System.out.println(\"4)\" + countries.<i>get</i>(0) );</pre>";
		var s11 = "<pre>        System.out.println(\"5)\" + countries.<i>indexOf</i>(\"Germany\") );</pre>";
		var s12 = "<pre>        System.out.println(\"6)\" + countries.<i>contains</i>(\"Ukraine\") );</pre>";
		var s13 = "<pre>        countries.<i>add</i>(\"China\");</pre><pre>        countries.<i>add</i>(2,\"USA\");</pre>";
		var s14 = "<pre>        System.out.println(\"7)\" + countries );</pre>";
		var s15 = "<pre>        countries.<i>set</i>(3,\"Japan\");</pre><pre>        System.out.println(\"8)\" + countries );</pre>";
		var s16 = "<pre>        countries.<i>remove</i>(2);</pre><pre>        countries.<i>remove</i>(\"Japan\");</pre>";
		var s17 = "<pre>        System.out.println(\"9)\" + countries );</pre><br>";
		var s18 = "<pre>        ArrayList &lt;String&gt; languages = <i>new</i> ArrayList&lt; &gt;();</pre>";
		var s19 = "<pre>        System.out.println(\"10)\" + languages.<i>isEmpty</i>())</pre>";
		var s20 = "<pre>        languages = (ArrayList &lt;String&gt;) countries.<i>clone</i>();";
		var s21 = "<pre>        System.out.println(\"11)\" + languages.<i>isEmpty</i>() + \": \" + languages);</pre><pre>        countries.clear();</pre>";
		var s22 = "<pre>        System.out.println(\"12)\" + countries.<i>isEmpty</i>())</pre>";
		var s23 = "<pre>    }</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = s14;
		document.getElementById("cl15").innerHTML = s15;
		document.getElementById("cl16").innerHTML = s16;
		document.getElementById("cl17").innerHTML = s17;
		document.getElementById("cl18").innerHTML = s18;
		document.getElementById("cl19").innerHTML = s19;
		document.getElementById("cl20").innerHTML = s20;
		document.getElementById("cl21").innerHTML = s21;
		document.getElementById("cl22").innerHTML = s22;
		document.getElementById("cl23").innerHTML = s23;
		document.getElementById("co1").innerHTML = "1) [Ukraine, Germany]<br>2) 2<br>3) [Ukraine]<br>4) Ukraine<br>5) 1<br>6) true";
		document.getElementById("co2").innerHTML = "7) [Ukraine, Germany, USA, China]<br>8) [Ukraine, Germany, USA, Japan]";
		document.getElementById("co3").innerHTML = "9) [Ukraine, Germany]<br>10) true";
		document.getElementById("co4").innerHTML = "11) false: [Ukraine, Germany]<br>12) true";
	}

	function clearr(){
		document.getElementById("cl1").innerHTML = "";
		document.getElementById("cl2").innerHTML = "";
		document.getElementById("cl3").innerHTML = "";
		document.getElementById("cl4").innerHTML = "";
		document.getElementById("cl5").innerHTML = "";
		document.getElementById("cl6").innerHTML = "";
		document.getElementById("cl7").innerHTML = "";
		document.getElementById("cl8").innerHTML = "";
		document.getElementById("cl9").innerHTML = "";
		document.getElementById("cl10").innerHTML = "";
		document.getElementById("cl11").innerHTML = "";
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("cl23").innerHTML = "";
		document.getElementById("co1").innerHTML = "";
		document.getElementById("co2").innerHTML = "";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
	}