function staq(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre>";
		var s2 = "<pre><i>import</i> java.util.Stack;</pre>";
		var s3 = "<pre><i>import</i> java.util.Queue;</pre>";
		var s4 = "<pre><i>import</i> java.util.Deque;</pre>";
		var s5 = "<pre><i>import</i> java.util.Collections;</pre>";
		var s6 = "<pre><i>import</i> java.util.ArrayDeque;</pre>";
		var s7 = "<pre><i>import</i> java.util.Arrays;</pre><br>";
		var s8 = "<pre><i>public class</i> Test{</pre>";
		var s9 = "<pre>    <i>public static void</i> main(String[] args) {</pre>";
		var s10 = "<pre>        <s>Stack stack = <i>new</i> Stack();</s></pre>";
		var s11 = "<pre>        Deque &lt;Character&gt; stack1= <i>new</i> ArrayDeque&lt; &gt;();</pre>";
		var s12 = "<pre>        Queue &lt;String&gt; stack2 = <i>new</i> Collections.asLifoQueue(<i>new</i> ArrayDeque&lt; &gt;());</pre>";
		var s13 = "<pre>        stack2.addAll(Arrays.asList(\"a\", \"b\", \"c\", \"d\", \"e\"));</pre>";
		var s14 = "<pre>        stack2.forEach(element -> System.out.println(element) ;</pre><pre>    }</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = s14;
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("cl23").innerHTML = "";
		document.getElementById("co1").innerHTML = "e<br>d<br>c<br>b<br>a";
		document.getElementById("co2").innerHTML = "";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
	}
	function stam(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre><i>import</i> java.util.Stack;</pre>";
		var s3 = "<pre><i>public class</i> Test{</pre>";
		var s4 = "<pre>    <i>public static void</i> main(String[] args) {</pre>";
		var s5 = "<pre>        Stack stack = <i>new</i> Stack();</pre>";
		var s6 = "<pre>        System.out.println(\"1)\" + stack.<i>empty</i>());</pre>";
		var s7 = "<pre>        stack.<i>push</i>(\"A\");</pre><pre>        stack.<i>push</i>(\"B\");</pre>";
		var s8 = "<pre>        stack.<i>push</i>(\"C\");</pre>";
		var s9 = "<pre>        System.out.println(\"2)\" + stack.<i>empty</i>());</pre>";
		var s10 = "<pre>        System.out.println(\"3)\" + stack.<i>peek</i>() + \": \" + stack);</pre>";
		var s11 = "<pre>        System.out.println(\"4)\" + stack.<i>pop</i>() + \": \" + stack);</pre>";
		var s12 = "<pre>        System.out.println(\"5)\" + stack.<i>search</i>(\"B\") );</pre>";
		var s13 = "<pre>        System.out.println(\"6)\" + stack.<i>search</i>(\"C\") );</pre><pre>    }</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("cl23").innerHTML = "";
		document.getElementById("co1").innerHTML = "1) true<br>2) false<br>3) C: [A, B, C]";
		document.getElementById("co2").innerHTML = "4) C: [A, B]<br>5) 1<br>6) -1";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
	}

	function clearr(){
		document.getElementById("cl1").innerHTML = "";
		document.getElementById("cl2").innerHTML = "";
		document.getElementById("cl3").innerHTML = "";
		document.getElementById("cl4").innerHTML = "";
		document.getElementById("cl5").innerHTML = "";
		document.getElementById("cl6").innerHTML = "";
		document.getElementById("cl7").innerHTML = "";
		document.getElementById("cl8").innerHTML = "";
		document.getElementById("cl9").innerHTML = "";
		document.getElementById("cl10").innerHTML = "";
		document.getElementById("cl11").innerHTML = "";
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("cl23").innerHTML = "";
		document.getElementById("co1").innerHTML = "";
		document.getElementById("co2").innerHTML = "";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
	}