function mass(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s3 = "<pre><i>public class</i> Test{</pre>";
		var s4 = "<pre>    <i>int</i> [] x = <i>new int</i> [5];</pre>";
		var s5 = "<pre>    <i>byte</i> [] b = {1, 2, 3, 4, 5};</pre>";
		var s6 = "<pre>    <i>char</i> [] y[][] = <i>new char</i>[6][][];</pre>";
		var s7 = "<pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = "";
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = " ";
		document.getElementById("cl9").innerHTML = " ";
		document.getElementById("cl10").innerHTML = " ";
		document.getElementById("cl11").innerHTML = " ";
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
	}
	function massgo(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre><i>public class</i> Test{</pre>";
		var s3 = "<pre>    <i>public static void</i> main(String[] args) {</pre>";
		var s4 = "<pre>        <i>int</i> [] x = <i>new int</i> [5];</pre>";
		var s5 = "<pre>        <i>byte</i> [] b = {1, 2, 3, 4, 5};</pre>";
		var s6 = "<pre>        <i>int</i> [] [] y = {{1, 2}, {3, 4}};</pre>";
		var s7 = "<pre>        <i>char</i> [] z[][] = <i>new char</i>[6][][];</pre><br>";
		var s8 = "<pre>        <i>for</i> (<i>int</i> i = 0; i < 5; i++){</pre>";
		var s9 = "<pre>            System.out.print( b[i] + \"  \");</pre><pre>        }</pre>";
		var s11 = "<pre>        <i>for</i> (<i>int</i> i = 0; i < 2; i++){</pre>";
		var s12 = "<pre>            System.out.print(\"\\n\");</pre>";
		var s13 = "<pre>            <i>for</i> (<i>int</i> j = 0; j < 2; j++){</pre>";
		var s14 = "<pre>                System.out.print( y[i] + \"  \");</pre>";
		var s15 = "<pre>            }</pre><pre>        }</pre><pre>    }</pre><pre>}</pre>"
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = "";
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = s14;
		document.getElementById("cl15").innerHTML = s15;
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("co1").innerHTML = "1, 2, 3, 4, 5, ";
		document.getElementById("co2").innerHTML = "1, 2, ";
		document.getElementById("co3").innerHTML = "3, 4, ";
		document.getElementById("co4").innerHTML = "";
	}

	function clearr(){
		document.getElementById("cl1").innerHTML = "";
		document.getElementById("cl2").innerHTML = "";
		document.getElementById("cl3").innerHTML = "";
		document.getElementById("cl4").innerHTML = "";
		document.getElementById("cl5").innerHTML = "";
		document.getElementById("cl6").innerHTML = "";
		document.getElementById("cl7").innerHTML = "";
		document.getElementById("cl8").innerHTML = "";
		document.getElementById("cl9").innerHTML = "";
		document.getElementById("cl10").innerHTML = "";
		document.getElementById("cl11").innerHTML = "";
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("co1").innerHTML = "";
		document.getElementById("co2").innerHTML = "";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
	}