
	function overfl(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre><i>class</i> A {</pre>";
		var s3 = "<pre>    <i>static</i> String x1;</pre>";
		var s4 = "<pre>    <i>static</i> { System.out.println(\"1: static initialized block of A\"); }</pre>";
		var s5 = "<pre>    { System.out.println(\"2: initialized block of A\"); }</pre>";
		var s6 = "<pre>    A(){</pre><pre>        System.out.println(\"3: constructor of A\");</pre><pre>    }</pre>";
		var s7 = "<pre>    A(<i>int</i> i){</pre><pre>        System.out.println(\"constructor of A with parameter\");</pre><pre>    }</pre><br>";
		var s8 = "<pre><i>class</i> B <i>extends</i> A {</pre>";
		var s9 = "<pre>    <i>static</i> { System.out.println(\"1: static initialized block of B\"); }</pre>";
		var s10 = "<pre>    { System.out.println(\"2: initialized block of B\"); }</pre>";
		var s11 = "<pre>    B(){</pre><pre>        System.out.println(\"3: constructor of B\");</pre><pre>    }</pre><br>";
		var s12 = "<pre><i>public class</i> Test {</pre>";
		var s13 = "<pre>    <i>public static void</i> main(String[] args) {</pre>";
		var s15 = "<pre>        A a = <i>new</i> A();</pre>";
		var s16 = "<pre>        System.out.println(\"---------------------\");</pre>";
		var s17 = "<pre>        A b1 = <i>new</i> B();</pre>";
		var s18 = "<pre>        System.out.println(\"---------------------\");</pre>";
		var s19 = "<pre>        B b2 = <i>new</i> B();</pre><pre>    }</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = s15;
		document.getElementById("cl16").innerHTML = s16;
		document.getElementById("cl17").innerHTML = s17;
		document.getElementById("cl18").innerHTML = s18;
		document.getElementById("cl19").innerHTML = s19;
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("co1").innerHTML = "static initialized block of A<br>initialized block of A<br>constructor of A";
		document.getElementById("co2").innerHTML = "---------------------";
		document.getElementById("co3").innerHTML = "static initialized block of B<br>initialized block of A<br>constructor of A";
		document.getElementById("co4").innerHTML = "initialized block of B<br>constructor of B<br>---------------------";
		document.getElementById("co5").innerHTML = "initialized block of A<br>constructor of A"
		document.getElementById("co6").innerHTML = "initialized block of B<br>constructor of B"
	}
	function overflm(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre><i>class</i> A {</pre>";
		var s3 = "<pre>    <i>static</i> String x1;</pre>";
		var s4 = "<pre>    <i>void</i> method1() {</pre><pre>        x1 = \"method of A\");</pre>";
		var s5 = "<pre>        System.out.println(x1);</pre><pre>    }</pre>";
		var s6 = "<pre>    <i>void</i> method2( <i>int</i> i) {</pre><pre>        x1 = \"method of A with argument\");</pre>";
		var s7 = "<pre>        System.out.println(x1 + i);</pre><pre>    }</pre>";
		var s8 = "<pre>    String method3() {</pre><pre>        x1 = \"method of A returns x1\");</pre>";
		var s9 = "<pre>        <i>return</i> x1;</pre><pre>    }</pre><pre>}</pre>";
		var s10 = "<pre><i>class</i> B <i>extends</i> A {</pre>";
		var s11 = "<pre>    <i>void</i> method1() {</pre><pre>        x1 = \"method of B\");</pre>";
		var s12 = "<pre>        System.out.println(x1);</pre><pre>    }</pre>";
		var s13 = "<pre>    <i>void</i> method2( <i>int</i> i) {</pre><pre>        x1 = \"method of B with argument\");</pre>";
		var s14 = "<pre>        System.out.println(x1 + i);</pre><pre>    }</pre>";
		var s15 = "<pre>    String method3() {</pre><pre>        x1 = \"method of B returns x1\");</pre>";
		var s16 = "<pre>        <i>return</i> x1;</pre><pre>    }</pre><pre>}</pre><br>";
		var s17 = "<pre><i>public class</i> Test {</pre>";
		var s18 = "<pre>    <i>public static void</i> main(String[] args) {</pre>";
		var s19 = "<pre>        A a = <i>new</i> A();</pre><pre>        A b = <i>new</i> B();</pre>";
		var s20 = "<pre>        a.method1();</pre><pre>        b.method1();</pre>";
		var s21 = "<pre>        a.method2(1);</pre><pre>        b.method1(2);</pre>";
		var s22 = "<pre>        System.out.println(a.method3());</pre><pre>        System.out.println(a.method3());</pre><pre>    }</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = s14;
		document.getElementById("cl15").innerHTML = s15;
		document.getElementById("cl16").innerHTML = s16;
		document.getElementById("cl17").innerHTML = s17;
		document.getElementById("cl18").innerHTML = s18;
		document.getElementById("cl19").innerHTML = s19;
		document.getElementById("cl20").innerHTML = s20;
		document.getElementById("cl21").innerHTML = s21;
		document.getElementById("cl22").innerHTML = s22;
		document.getElementById("co1").innerHTML = "method of A";
		document.getElementById("co2").innerHTML = "method of B";
		document.getElementById("co3").innerHTML = "method of A with argument 1";
		document.getElementById("co4").innerHTML = "method of B with argument 2";
		document.getElementById("co5").innerHTML = "method of A returns x1";
		document.getElementById("co6").innerHTML = "method of B returns x1"
	}
	function overrid(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><br>";
		var s2 = "<pre><i>class</i> A {</pre>";
		var s3 = "<pre>    <i>static</i> String x1;</pre>";
		var s4 = "<pre>    <i>void</i> method( <i>int</i> i) {</pre><pre>        x1 = \"method of A with int-argument \");</pre>";
		var s5 = "<pre>        System.out.println(x1 + i);</pre><pre>    }</pre>";
		var s6 = "<pre>    <i>void</i> method( <i>double</i> i) {</pre><pre>        x1 = \"method of A with double-argument \");</pre>";
		var s7 = "<pre>        System.out.println(x1 + i);</pre><pre>    }</pre>";
		var s8 = "<pre>    <i>void</i> method( <i>char</i> i) {</pre><pre>        x1 = \"method of A with char-argument \");</pre>";
		var s9 = "<pre>        System.out.println(x1 + i);</pre><pre>    }</pre><pre>}</pre><br>";
		var s10 = "<pre><i>public class</i> Test {</pre>";
		var s11 = "<pre>    <i>public static void</i> main(String[] args) {</pre>";
		var s12 = "<pre>        A a = <i>new</i> A();</pre>";
		var s13 = "<pre>        a.method(1);</pre>";
		var s14 = "<pre>        a.method(1.5);</pre>";
		var s15 = "<pre>        a.method('a');</pre>";
		var s16 = "<pre>    }</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = s14;
		document.getElementById("cl15").innerHTML = s15;
		document.getElementById("cl16").innerHTML = s16;
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("co1").innerHTML = "method of A with int-argument 1";
		document.getElementById("co2").innerHTML = "method of A with double-argument 1";
		document.getElementById("co3").innerHTML = "method of A with char-argument 1";
		document.getElementById("co4").innerHTML = "";
		document.getElementById("co5").innerHTML = "";
		document.getElementById("co6").innerHTML = ""
	}

	function clearr(){
		document.getElementById("cl1").innerHTML = "";
		document.getElementById("cl2").innerHTML = "";
		document.getElementById("cl3").innerHTML = "";
		document.getElementById("cl4").innerHTML = "";
		document.getElementById("cl5").innerHTML = "";
		document.getElementById("cl6").innerHTML = "";
		document.getElementById("cl7").innerHTML = "";
		document.getElementById("cl8").innerHTML = "";
		document.getElementById("cl9").innerHTML = "";
		document.getElementById("cl10").innerHTML = "";
		document.getElementById("cl11").innerHTML = "";
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("co1").innerHTML = "";
		document.getElementById("co2").innerHTML = "";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
		document.getElementById("co5").innerHTML = "";
		document.getElementById("co6").innerHTML = "";
		document.getElementById("co7").innerHTML = "";
		document.getElementById("co8").innerHTML = "";
		document.getElementById("co9").innerHTML = "";
		document.getElementById("co10").innerHTML = "";
	}