function fdec(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre>";
		var s2 = "<pre><i>import</i> java.io.File;</pre>";
		var s3 = "<pre><i>import</i> java.io.RandomAccessFile;</pre><br>";
		var s4 = "<pre><i>public class</i> Test{</pre>";
		var s5 = "<pre>    <u>//Creating file object</u></pre>";
		var s6 = "<pre>    File dir = <i>new</i> File(\" \");</pre>";
		var s7 = "<pre>    <u>//Creating absolute path</u></pre>";
		var s8 = "<pre>    File dir1 = <i>new</i> File(\"C:\\\\Users\\\\ODMEN\\\\eclipse-workspace\\\\MyTryings\\\\src\\\\output\\\\filelist\");</pre>";
		var s9 = "<pre>    <u>//Creating abstract path</u></pre>";
		var s10 = "<pre>    File dir2 = <i>new</i> File(\"src/output/filelist\");</pre><br>";
		var s11 = "<pre>    <u>//Creating file object  in the root of project</u></pre>";
		var s12 = "<pre>    File file = <i>new</i> File(\"Hello.txt\");</pre>";
		var s13 = "<pre>    <u>//Creating file object in other folder</u></pre>";
		var s14 = "<pre>    File file1 = <i>new</i> File(\"src/output/filelist\",\"Hello.txt\");</pre>";
		var s15 = "<pre>    File file2 = <i>new</i> File(dir1, \"Hello.txt\");</pre>";
		var s16 = "<pre>    File file3 = <i>new</i> File(\"src/output/filelist/Hello.txt\");</pre><br>";
		var s17 = "<pre>    RandomAccessFile acc1 = <i>new</i> RandomAccessFile(file, \"r\");<u>  //file may be only ridden</u></pre>";
		var s18 = "<pre>    RandomAccessFile acc1 = <i>new</i> RandomAccessFile(file, \"rw\");<u>  //file may be ridden and written</u></pre>";
		var s19 = "<pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = s14;
		document.getElementById("cl15").innerHTML = s15;
		document.getElementById("cl16").innerHTML = s16;
		document.getElementById("cl17").innerHTML = s17;
		document.getElementById("cl18").innerHTML = s18;
		document.getElementById("cl19").innerHTML = s19;
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("cl23").innerHTML = "";
		document.getElementById("co1").innerHTML = "";
		document.getElementById("co2").innerHTML = "";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
	}
	function fpath(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre>";
		var s2 = "<pre><i>import</i> java.io.File;</pre><br>";
		var s3 = "<pre><i>class</i> FileMeth{</pre>";
		var s4 = "<pre>    <i>void</i> pathMeth(File dirPath) <i>throws</i> IOException{</pre>";
		var s5 = "<pre>        System.out.print(\"\\n\");</pre>";
		var s6 = "<pre>        System.out.print(dirPath.getName() + \".getPath() = \"+dirPath.getPath());</pre>";
		var s7 = "<pre>        System.out.print(dirPath.getName() + \".getAbsolutePath() = \"+dirPath.getAbsolutePath());</pre>";
		var s8 = "<pre>        System.out.print(dirPath.getName() + \".getCanonicalPath() = \"+dirPath.getCanonicalPath()); <u>throws exception</u></pre>";
		var s9 = "<pre>        System.out.print(dirPath.getName() + \".getParent() = \"+dirPath.getParent());</pre><pre>    }</pre><pre>}</pre><br>";
		var s10 = "<pre><i>public class</i> Test{</pre>";
		var s11 = "<pre>    <i>public static void</i> main(String[] args) <i>throws</i> IOException{</pre>";
		var s12 = "<pre>        FileMeth check = <i>new</i> FileMeth();</pre><br>";
		var s13 = "<pre>        File dir = <i>new</i> File(\" \");</pre>";
		var s14 = "<pre>        File dir2 = <i>new</i> File(\"src/output/filelist\");</pre>";
		var s15 = "<pre>        File file = <i>new</i> File(\"src/output/filelist/Hello.txt\");</pre><br>";
		var s16 = "<pre>        check.pathMeth(dir);</pre>";
		var s17 = "<pre>        check.pathMeth(dir2);</pre>";
		var s18 = "<pre>        check.pathMeth(file);</pre>";
		var s19 = "<pre>        System.out.println(new File(\".\").getCanonicalPath());	<u>//current</u></pre>";
		var s20 = "<pre>        System.out.println(new File(\"..\").getCanonicalPath());	<u>//root</u></pre>";
		var s21 = "<pre>    }</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = s14;
		document.getElementById("cl15").innerHTML = s15;
		document.getElementById("cl16").innerHTML = s16;
		document.getElementById("cl17").innerHTML = s17;
		document.getElementById("cl18").innerHTML = s18;
		document.getElementById("cl19").innerHTML = s19;
		document.getElementById("cl20").innerHTML = s20;
		document.getElementById("cl21").innerHTML = s21;
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("cl23").innerHTML = "";
		document.getElementById("co1").innerHTML = "<br>.getPath() =<br>.getAbsolutePath() = C:\\Users\\ODMEN\\eclipse-workspace\\MyTryings<br>.getCanonicalPath() = C:\\Users\\ODMEN\\eclipse-workspace\\MyTryings<br>.getParent() = null";
		document.getElementById("co2").innerHTML = "<br>filelist.getPath() = src\\output\\filelist<br>.getAbsolutePath() = C:\\Users\\ODMEN\\eclipse-workspace\\MyTryings\\src\\output\\filelist<br>filelist.getCanonicalPath() = C:\\Users\\ODMEN\\eclipse-workspace\\MyTryings\\src\\output\\filelist<br>filelist.getParent() = src\\output";
		document.getElementById("co3").innerHTML = "<br>Hello.txt.getPath() = Hello.txt<br>Hello.txt.getAbsolutePath() = C:\\Users\\ODMEN\\eclipse-workspace\\MyTryings\\src\\output\\filelist\\Hello.txt<br>Hello.txt.getCanonicalPath() = C:\\Users\\ODMEN\\eclipse-workspace\\MyTryings\\src\\output\\filelist\\Hello.txt<br>Hello.txt.getParent() = null";
		document.getElementById("co4").innerHTML = "C:\\Users\\ODMEN\\eclipse-workspace\\MyTryings<br>C:\\Users\\ODMEN\\eclipse-workspace";
	}
	function fmeth(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><pre><i>import</i> java.io.File;</pre><br>";
		var s2 = "<pre><i>class</i> FileMeth{</pre><pre>    <i>void</i> boolMeth(File file){</pre>";
		var s3 = "<pre>        System.out.print(\"\\n\");</pre><pre>        System.out.print(file.getName() + \".isAbsolute() = \");</pre>";
		var s4 = "<pre>        System.out.println(file.isAbsolute());</pre><pre>        System.out.print(file.getName() + \".isDirectory() = \");</pre>";
		var s5 = "<pre>        System.out.println(file.isDirectory());</pre>";
		var s6 = "<pre>        System.out.print(file.getName() + \".isFile() = \");</pre><pre>        System.out.println(file.isFile());</pre><pre>    }</pre><br>";
		var s7 = "<pre>    <i>void</i> listMeth(File dirPath){</pre><pre>        System.out.println(\"\\n\");</pre>";
		var s8 = "<pre>        System.out.println(dirPath.getName());</pre><pre>        System.out.println(dirPath.length());</pre><br>";
		var s9 = "<pre>        System.out.println(\"Method list() returns: \");</pre><pre>        <i>for</i>(String item : dirPath.list()){</pre>";
		var s10 = "<pre>            System.out.println(\"> \" + item);</pre><pre>        }</pre>";
		var s11 = "<pre>        System.out.println(\"Method listFiles() returns: \");</pre><pre>        <i>for</i>(String item : dirPath.listFiles()){</pre>";
		var s12 = "<pre>            System.out.println(\"> \" + item);</pre><pre>        }</pre>";
		var s13 = "<pre>        System.out.println(\"Method listRoots() returns: \");</pre>";
		var s14 = "<pre>        <i>for</i>(String item : dirPath.listRoots()){</pre>";
		var s15 = "<pre>            System.out.println(\"> \" + item);</pre><pre>        }</pre><br>";
		var s16 = "<pre>        <i>if</i>(dirPath.isDirectory()){</pre><pre>            <i>for</i>(File item : dirPath.listFiles()){</pre>";
		var s17 = "<pre>                <i>if</i>(item.isDirectory()){</pre>";
		var s18 = "<pre>                    System.out.println(item.getName() + \"\\t folder\");</pre><pre><pre>                } <i>else</i> {</pre>";
		var s19 = "<pre>                    System.out.println(item.getName() + \"\\t directory\");</pre><pre><pre>                }</pre><pre>            }</pre><pre>        }</pre><pre>    }</pre><pre>}</pre>";
		var s20 = "<pre><i>public class</i> Test{</pre><pre>    <i>public static void</i> main(String[] args){</pre>";
		var s21 = "<pre>        FileMeth check = <i>new</i> FileMeth();</pre><br><pre>        File dir = <i>new</i> File(\"src/output/filelist\");</pre>";
		var s22 = "<pre>        File file = <i>new</i> File(\"src/output/filelist/Hello.txt\");</pre><br><pre>        check.boolMeth(dir);</pre><pre>        check.boolMeth(file);</pre>";
		var s23 = "<pre>        check.listMeth(dir);</pre><pre>    }</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = s14;
		document.getElementById("cl15").innerHTML = s15;
		document.getElementById("cl16").innerHTML = s16;
		document.getElementById("cl17").innerHTML = s17;
		document.getElementById("cl18").innerHTML = s18;
		document.getElementById("cl19").innerHTML = s19;
		document.getElementById("cl20").innerHTML = s20;
		document.getElementById("cl21").innerHTML = s21;
		document.getElementById("cl22").innerHTML = s22;
		document.getElementById("cl23").innerHTML = s23;
		document.getElementById("co1").innerHTML = "<br>filelist.isAbsolute() = false<br>filelist.isDirectory() = true<br>filelist.isFile() = false<br><br>Hello.isAbsolute() = false<br>Hello.isDirectory() = false<br>Hello.isFile() = false<br>";
		document.getElementById("co2").innerHTML = "<br>filelist<br>4096<br>Method list() returns:<br>> somefile1.txt<br>> somefile2.txt<br>> somefolder";
		document.getElementById("co3").innerHTML = "Method listFiles() returns:<br>> src\\output\\filelist\\sometext1.txt<br>> src\\output\\filelist\\sometext2.txt<br>> src\\output\\filelist\\somefolder.txt";
		document.getElementById("co4").innerHTML = "Method listRoots() returns:<br>> C:\\<br>> D:\\<br>> E:\\<br>sometext1.txt\tfile<br>sometext2.txt\tfile<br>somefolder\tfolder";
	}
	function fdometh(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><pre><i>import</i> java.io.File;</pre><pre><i>import</i> java.io.IOException;</pre><br>";
		var s2 = "<pre>    <i>void</i> fileOperations(File path) <i>throws</i> IOException {</pre>";
		var s3 = "<pre>        File myFile = <i>new</i> File(path, \"myFile.txt\");</pre><pre>        System.out.println(\"myFile.exists() = \"+ myFile.exists());</pre>";
		var s4 = "<pre>        System.out.println(\"myFile.canRead() = \"+ myFile.canRead());</pre>";
		var s5 = "<pre>        System.out.println(\"myFile.canWrite() = \"+ myFile.canWrite());</pre>";
		var s6 = "<pre>        <i>boolean</i> created = myFile.createNewFile(); <u>//throws exception</u></pre>";
		var s7 = "<pre>        <i>if</i> (created)</pre><pre>            System.out.println(\"myFile.createNewFile() = File has been created\");</pre>";
		var s8 = "<pre>        System.out.println(\"myFile.exists() = \"+ myFile.exists());</pre>";
		var s9 = "<pre>        System.out.println(\"myFile.canRead() = \"+ myFile.canRead());</pre>";
		var s10 = "<pre>        System.out.println(\"myFile.canWrite() = \"+ myFile.canWrite());</pre>";
		var s11 = "<pre>        File newFile = <i>new</i> File(path, \"newFile.txt\");</pre><pre>        <i>boolean</i> renamed = myFile.renameTo(newFile);</pre>";
		var s12 = "<pre>        <i>if</i> (renamed)</pre><pre>            System.out.println(\"myFile.renameTo(newFile) = File has been renamed\");</pre>";
		var s13 = "<pre>        System.out.println(path.getName() + \"-folder contains: \");</pre>";
		var s14 = "<pre>        <i>for</i>(String item: dirPath : dirPath.list()){</pre><pre>            System.out.println(\"> \" + item);</pre><pre>        }</pre>";
		var s15 = "<pre>        <i>boolean</i> deleted = newFile.delete();</pre>";
		var s16 = "<pre>        <i>if</i> (deleted)</pre><pre>            System.out.println(\"newFile.delete() = File has been deleted\");</pre>";
		var s17 = "<pre>        System.out.println(path.getName() + \"-folder contains: \");</pre>";
		var s18 = "<pre>        <i>for</i>(String item: dirPath : dirPath.list()){</pre><pre>            System.out.println(\"> \" + item);</pre><pre>        }</pre><pre>    }</pre><pre>}</pre>";
		var s19 = "<pre><i>public class</i> Test{</pre><pre>    <i>public static void</i> main(String[] args) <i>throws</i> IOException{</pre>";
		var s20 = "<pre>        FileMeth check = <i>new</i> FileMeth();</pre><br><pre>        File dir = <i>new</i> File(\"src/output/filelist\");</pre>";
		var s21 = "<pre>        check.fileOperations(dir);</pre><pre>    }</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = s14;
		document.getElementById("cl15").innerHTML = s15;
		document.getElementById("cl16").innerHTML = s16;
		document.getElementById("cl17").innerHTML = s17;
		document.getElementById("cl18").innerHTML = s18;
		document.getElementById("cl19").innerHTML = s19;
		document.getElementById("cl20").innerHTML = s20;
		document.getElementById("cl21").innerHTML = s21;
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("cl23").innerHTML = "";
		document.getElementById("co1").innerHTML = "myFile.exists() = false<br>myFile.canRead() = false<br>myFile.canWrite() = false<br>myFile.createNewFile() = File has been created";
		document.getElementById("co2").innerHTML = "myFile.exists() = true<br>myFile.canRead() = true<br>myFile.canWrite() = true<br>myFile.renameTo(newFile) = File has been renamed";
		document.getElementById("co3").innerHTML = "filelist-foler contains: <br>> newFile.txt<br>> somefile1.txt<br>> somefile2.txt<br>> somefolder";
		document.getElementById("co4").innerHTML = "newFile.delete() = File has been deleted<br>filelist-foler contains: <br>> somefile1.txt<br>> somefile2.txt<br>> somefolder";
	}
	function dirdometh(){
		var s1 = "<pre><i>package</i> com.mypackage;</pre><pre><i>import</i> java.io.File;</pre><br><pre><i>import</i> java.io.IOException;</pre><br>";
		var s2 = "<pre><i>class</i> FileMeth{</pre><pre>    <i>void</i> dirOperations(File path) <i>throws</i> IOException {</pre>";
		var s3 = "<pre>        File dir = <i>new</i> File(path, \"Dir\");</pre><pre>        System.out.print(\"dir.exists() = \"+ dir.exists());</pre>";
		var s4 = "<pre>        <i>boolean</i> created = dir.mkdir(); <u>//throws exception</u></pre>";
		var s5 = "<pre>        <i>if</i> (created)</pre><pre>            System.out.print(\"dir.mkdir() = Folder has been created\");</pre>";
		var s6 = "<pre>        System.out.print(\"dir.exists() = \"+ dir.exists());</pre>";
		var s7 = "<pre>        System.out.print(\"dir.canRead() = \"+ dir.canRead());</pre>";
		var s8 = "<pre>        System.out.print(\"dir.canWrite() = \"+ dir.canWrite());</pre>";
		var s9 = "<pre>        File newDir = <i>new</i> File(path, \"newDir.txt\");</pre><pre>        <i>boolean</i> renamed = dir.renameTo(newDir);</pre>";
		var s10 = "<pre>        <i>if</i> (renamed)</pre><pre>            System.out.print(\"dir.renameTo(newDir) = Folder has been renamed\");</pre>";
		var s11 = "<pre>        System.out.print(path.getName() + \"-folder contains: \");</pre>";
		var s12 = "<pre>        <i>for</i>(String item: dirPath : dirPath.list()){</pre><pre>            System.out.println(\"> \" + item);</pre><pre>        }</pre>";
		var s13 = "<pre>        <i>boolean</i> deleted = newDir.delete();</pre><pre>        <i>if</i> (deleted)</pre><pre>            System.out.print(\"newDir.delete() = Folder has been deleted\");</pre>";
		var s14 = "<pre>        System.out.print(path.getName() + \"-folder contains: \");</pre>";
		var s15 = "<pre>        <i>for</i>(String item: dirPath : dirPath.list()){</pre>";
		var s16 = "<pre>            System.out.println(\"> \" + item);</pre><pre>        }</pre><pre>    }</pre><pre>}</pre>";
		var s17 = "<pre><i>public class</i> Test{</pre>";
		var s18 = "<pre>    <i>public static void</i> main(String[] args){</pre>";
		var s19 = "<pre>        FileMeth check = <i>new</i> FileMeth();</pre><br>";
		var s20 = "<pre>        File dir = <i>new</i> File(\"src/output/filelist\");</pre>";
		var s21 = "<pre>        check.dirOperations(dir)</pre>";
		var s22 = "<pre>    }</pre><pre>}</pre>";
		document.getElementById("cl1").innerHTML = s1;
		document.getElementById("cl2").innerHTML = s2;
		document.getElementById("cl3").innerHTML = s3;
		document.getElementById("cl4").innerHTML = s4;
		document.getElementById("cl5").innerHTML = s5;
		document.getElementById("cl6").innerHTML = s6;
		document.getElementById("cl7").innerHTML = s7;
		document.getElementById("cl8").innerHTML = s8;
		document.getElementById("cl9").innerHTML = s9;
		document.getElementById("cl10").innerHTML = s10;
		document.getElementById("cl11").innerHTML = s11;
		document.getElementById("cl12").innerHTML = s12;
		document.getElementById("cl13").innerHTML = s13;
		document.getElementById("cl14").innerHTML = s14;
		document.getElementById("cl15").innerHTML = s15;
		document.getElementById("cl16").innerHTML = s16;
		document.getElementById("cl17").innerHTML = s17;
		document.getElementById("cl18").innerHTML = s18;
		document.getElementById("cl19").innerHTML = s19;
		document.getElementById("cl20").innerHTML = s20;
		document.getElementById("cl21").innerHTML = s21;
		document.getElementById("cl22").innerHTML = s22;
		document.getElementById("cl23").innerHTML = "";
		document.getElementById("co1").innerHTML = "dir.exists() = false<br>dir.mkdir() = Folder has been created";
		document.getElementById("co2").innerHTML = "dir.exists() = true<br>dir.canRead() = true<br>dir.canWrite() = true<br>dir.renameTo(newDir) = Folder has been renamed";
		document.getElementById("co3").innerHTML = "filelist-foler contains: <br>> newDir<br>> somefile1.txt<br>> somefile2.txt<br>> somefolder";
		document.getElementById("co4").innerHTML = "newDir.delete() = Folder has been deleted<br>filelist-foler contains: <br>> somefile1.txt<br>> somefile2.txt<br>> somefolder";
	}
	function clearr(){
		document.getElementById("cl1").innerHTML = "";
		document.getElementById("cl2").innerHTML = "";
		document.getElementById("cl3").innerHTML = "";
		document.getElementById("cl4").innerHTML = "";
		document.getElementById("cl5").innerHTML = "";
		document.getElementById("cl6").innerHTML = "";
		document.getElementById("cl7").innerHTML = "";
		document.getElementById("cl8").innerHTML = "";
		document.getElementById("cl9").innerHTML = "";
		document.getElementById("cl10").innerHTML = "";
		document.getElementById("cl11").innerHTML = "";
		document.getElementById("cl12").innerHTML = "";
		document.getElementById("cl13").innerHTML = "";
		document.getElementById("cl14").innerHTML = "";
		document.getElementById("cl15").innerHTML = "";
		document.getElementById("cl16").innerHTML = "";
		document.getElementById("cl17").innerHTML = "";
		document.getElementById("cl18").innerHTML = "";
		document.getElementById("cl19").innerHTML = "";
		document.getElementById("cl20").innerHTML = "";
		document.getElementById("cl21").innerHTML = "";
		document.getElementById("cl22").innerHTML = "";
		document.getElementById("cl23").innerHTML = "";
		document.getElementById("co1").innerHTML = "";
		document.getElementById("co2").innerHTML = "";
		document.getElementById("co3").innerHTML = "";
		document.getElementById("co4").innerHTML = "";
	}